export type ViewType =
  | 'login'
  | 'forgot'
  | 'mobilebankid'
  | 'mobilebankidpending'
  | 'mobilebankidapproved'
  | 'authbankidlocal'
  | 'authbankidlocalsuccess'
  | 'twofactor'
  | 'newpassword'
  | 'resetpasswordemail'
  | 'nocodereceived'
  | 'noemailreceived'
  | 'dashboard-view'
  | 'authenticated-view'
