export type ViewType =
  | 'login'
  | 'forgot'
  | 'mobilebankid'
  | 'mobilebankidpending'
  | 'mobilebankidapproved'
  | 'bankiddevice'
  | 'bankiddeviceapproved'
  | 'twofactor'
  | 'newpassword'
  | 'resetpasswordemail'
  | 'nocodereceived'
  | 'noemailreceived'