export type ViewType =
  | 'login'
  | 'forgot'
  | 'authbankidqr'
  | 'authbankidqrpending'
  | 'authbankidqrsuccess'
  | 'authbankidlocal'
  | 'authbankidlocalsuccess'
  | 'auth2faverify'
  | 'newpassword'
  | 'authpasswordresetsent'
  | 'nocodereceived'
  | 'authpasswordresetretry'
  | 'dashboard-view'
  | 'authenticated-view'
