export type ViewType =
  | 'login'
  | 'forgot-password'
  | 'auth-bankid-qr'
  | 'auth-bankid-qr-pending'
  | 'auth-bankid-qr-success'
  | 'auth-bankid-local'
  | 'auth-bankid-local-success'
  | 'auth-2fa-verify'
  | 'new-password'
  | 'auth-password-reset-sent'
  | 'auth-2fa-retry'
  | 'auth-password-reset-retry'
  | 'dashboard-view'
  | 'authenticated-view'
