export type ViewType =
  | 'login'
  | 'forgotpassword'
  | 'authbankid-qr'
  | 'authbankid-qr-pending'
  | 'authbankid-qr-success'
  | 'authbankid-local'
  | 'authbankid-local-success'
  | 'auth2faverify'
  | 'newpassword'
  | 'authpassword-reset-sent'
  | 'auth2faretry'
  | 'authpassword-reset-retry'
  | 'dashboard-view'
  | 'authenticated-view'
